### ISSUE TITLE
安装依赖报错了,似乎是个内网包地址

### ISSUE THREAD

**Issue by slothvips** [baozouai/react-source-study#10]
error An unexpected error occurred: "http://192.168.1.3:4873/@babel%2ftraverse/-/traverse-7.10.3.tgz: connect ETIMEDOUT 192.168.1.3:4873".

**Comment by baozouai** [comment]
> error An unexpected error occurred: "http://192.168.1.3:4873/@babel%2ftraverse/-/traverse-7.10.3.tgz: connect ETIMEDOUT 192.168.1.3:4873".

看package.json没问题

**Comment by wangyiliangnet** [comment]
是 yarn.lock 的问题，resolve 的都是上面那个内网 ip 地址。

**Comment by wangyiliangnet** [comment]
把 yarn.lock 里的 http://192.168.1.3:4873/ 批量替换成 https://registry.yarnpkg.com 就行了
